### ISSUE TITLE
The accuracy on FalseQA

### ISSUE THREAD

**Issue by BAOOOOOM** [shizhediao/R-Tuning#3]
I had the pleasure of reading your paper and found it very interesting, but I have a question. The 5.4 part of the paper uses the rejection rate metrics, while the FalseQA dataset officially uses Precision, Accuracy, Recall, etc. May I ask how R-Tuning performs on these metrics?

**Comment by shizhediao** [comment]
Hi,
Thanks for your attention!
The official FalseQA dataset contains both False Premise Questions (unanswerable) and True Premise Questions. Because the authors fine-tune language models to discriminate them, they could use accuracy, precision, and recall for the binary classification. 
Inspired by [1] which proposed a refusal-benchmark, in our work, we focused on the rejection ability and only used the False Premise Questions which we expected our model to reject since they are all unanswerable. Therefore, we only adopt the rejection rate as the metric.
Thanks!

[1] Prudent Silence or Foolish Babble? Examining Large Language Models’ Responses to the Unknown
